# Generated by Django 4.2.4 on 2023-08-15 17:53

from django.db import migrations

# https://dev.to/koladev/writing-custom-migrations-in-django-3eli

# python manage.py makemigrations user --empty
# python manage.py makemigrations user --empty -n update_fn_and_ln


def update_user(user):
    if not user.first_name and not user.last_name:
        email = str(user.email)
        full_name = email.split("@")[0]
        if "_" in full_name:
            fn, ln = full_name.split("_")
            user.first_name = fn
            user.last_name = ln
    return user


def migrate_to_user_model(apps, schema_editor):
    User = apps.get_model("user", "User")
    users = [update_user(user) for user in list(User.objects.all())]
    User.objects.bulk_update(users, ["first_name", "last_name"])


class Migration(migrations.Migration):
    dependencies = [("user", "0001_initial")]

    operations = [migrations.RunPython(migrate_to_user_model)]
