# Generated by Django 4.2.4 on 2023-08-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_update_fn_and_ln'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
