# Generated by Django 4.2.4 on 2023-08-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
