# Generated by Django 4.2.4 on 2023-08-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_collaborator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-id']},
        ),
    ]
